title: Livro Digital 2016
tagline: Liberdade de Expressão
description: >
  Projeto de redação dos alunos do 9º ano de 2016. As redações são de temas à escolha dos autores. Navegue, leia, compartilhe e comente.
baseurl: "/livro-digital-2016" # the subpath of your site, e.g. /blog
url: "http://objetivoweb.com.br"

# Build settings
markdown: kramdown
keep_files: 
  - ftpsync.settings

sass:
  style: compressed

gems:
  - jekyll-coffeescript

collections:
  textos:
    output: true
    permalink: /:path/
  unidades:
    output: true

defaults:
  - scope:
      path: ""
      type: textos
    values:
      layout: texto
  - scope:
      path: ""
      type: unidades
    values:
      layout: unidade
