title: Livro Digital 2016
tagline: Liberdade de Expressão
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/livro-digital-2016" # the subpath of your site, e.g. /blog
url: "https://objetivoweb.github.io"

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript

collections:
  textos:
    output: true
    permalink: /:path/
  unidades:
    output: true

defaults:
  - scope:
      path: ""
      type: textos
    values:
      layout: texto
  - scope:
      path: ""
      type: unidades
    values:
      layout: unidade
